background = 1B211C
foreground = E3DFC8
cursor-color = E8A873
cursor-text = 1B211C
selection-background = 2E372B
selection-foreground = E3DFC8

palette = 0=#1B211C
palette = 1=#C17A5E
palette = 2=#8FAE6F
palette = 3=#D9B96C
palette = 4=#6C8FA0
palette = 5=#A98BA0
palette = 6=#6FA894
palette = 7=#E3DFC8
palette = 8=#3A443A
palette = 9=#D48F70
palette = 10=#A3C283
palette = 11=#E8CB86
palette = 12=#84A6B5
palette = 13=#BEA0B5
palette = 14=#86BFAB
palette = 15=#F5F1DE
