background {
  color = rgba(1B211Cff)
}

input-field {
  size = 300, 60
  outline_thickness = 3
  dots_size = 0.25
  dots_spacing = 0.3
  outer_color = rgba(D9B96Cff)
  inner_color = rgba(232B22ee)
  font_color = rgba(E3DFC8ff)
  fade_on_empty = false
  placeholder_text = <span foreground="##E3DFC8">Password...</span>
  hide_input = false
}

label {
  text = cmd[update:1000] echo "$TIME"
  color = rgba(E3DFC8ff)
  font_size = 64
  font_family = JetBrainsMono Nerd Font
}

label {
  text = $LAYOUT
  color = rgba(8FAE6Fff)
  font_size = 14
  font_family = JetBrainsMono Nerd Font
}
