background            #1B211C
foreground            #E3DFC8
cursor                #E8A873
cursor_text_color     #1B211C
selection_background  #2E372B
selection_foreground  #E3DFC8

color0  #1B211C
color1  #C17A5E
color2  #8FAE6F
color3  #D9B96C
color4  #6C8FA0
color5  #A98BA0
color6  #6FA894
color7  #E3DFC8
color8  #3A443A
color9  #D48F70
color10 #A3C283
color11 #E8CB86
color12 #84A6B5
color13 #BEA0B5
color14 #86BFAB
color15 #F5F1DE
